### ISSUE TITLE
Panel gerbers is very large - possibly entire work surface

### ISSUE THREAD

**Issue by jacobsvensmark** [Testbild-synth/HAGIWO-040-VCS-Eurorack#1]
Hi

Very cool project. This is not necessarily a big issue (or an issue at all) but when I try to upload the gerbers for the panel to JLCPCB, it thinks that the PCB is huge - possibly it thinks the pcb is the entire KICAD work surface, not only the actual panel. I tried re-exporting gerbers from the kicad files, with the same result. Hope you have some insight! Thanks.

EDIT: Also, you write that it is designed for the "DG211/DG411" ICs, but write only the DG211 in the BOM. Could I use the DG411 as a drop in replacement, or would it take modification of sorts? What is the difference between using the two?

**Comment by Testbild-synth** [comment]
Hi, I had some issues with this previously due to kicad project settings.
I'll fix it today and notify you once I have

jacobsvensmark ***@***.***> schrieb am Mo., 11. Sep. 2023,
09:08:

**Comment by Testbild-synth** [comment]
fixed the pcb export, new file should work i checked in two different gerber viewers.
Regarding the chip, yes its a drop in replacement DG411 is a newer version that may have slightly different specs like a few nanoseconds different switch time. for our purposes it should not matter so use whichever one is easier to source for you

**Comment by jacobsvensmark** [comment]
Nice, thanks!

**Comment by jacobsvensmark** [comment]
Actually, the github repo does not appear to have been updated - last updated a year ago or thereabouts.

**Comment by Testbild-synth** [comment]
sorry, check again now idk what was wrong with my gitkraken yesterday
